# Generated by Django 6.0.5 on 2026-06-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_brname_student_branche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
